### PR TITLE
updated v3.5.3

### PR DESCRIPTION
**Pull request by densamoilov**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by densamoilov** [comment]
@conda-forge-admin, please rerender

**Comment by densamoilov** [comment]
@conda-forge-admin, please rerender

**Comment by densamoilov** [comment]
@conda-forge-admin, please rerender

**Comment by densamoilov** [comment]
Hi @xhochy, is there anything else I need to do to get this PR merged?

**Review by xhochy — APPROVED** [review]

**Comment by xhochy** [comment]
You need to fix the windows build ;)

**Comment by densamoilov** [comment]
@xhochy, but the build is not broken, it's a tests that fails. Is it required to make all tests pass?

**Comment by xhochy** [comment]
You can also skip tests, but CI needs to be green.

**Pull request merged**
